# -*- coding: utf-8 -*-
"""Etched FP4 Multiplier Take-Home -- colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1016tO9R36ukHb7jQ7GHlXbhLmgEhwzfP
"""

# !pip install ml-dtypes==0.5.1   # (Colab cell magic; uncomment in Colab)
import itertools
import numpy as np
import ml_dtypes
assert ml_dtypes.__version__ == "0.5.1"
from ml_dtypes import uint4, float4_e2m1fn
from numpy import float32, int16
from typing import List, Dict

# Valid operations - do NOT modify this. For simplicity, each costs the
# same amount.
NOT = lambda x: not x
OR = lambda x, y: x | y
AND = lambda x, y: x & y
XOR = lambda x, y: x ^ y

# Example remapping showing how you can use 0b0000 for both +0 and -0, if you like

# We MAY ALSO swap items around - instead of 1.5 being 0b0011 and 1 being 0b0010,
# you could swap these we could make it so that 1 was 0b0011 and 1.5 was 0b0010.

# Custom remap: code {s,e1,e0,m}, value = (-1)^s * (1+2m) * 2^(e-1),
# codes 0111 and 1111 both mean zero (the circuit accepts either).
INPUT_REMAP = {
    float4_e2m1fn(0):    uint4(0b0111),
    float4_e2m1fn(0.5):  uint4(0b0000),
    float4_e2m1fn(1):    uint4(0b0010),
    float4_e2m1fn(1.5):  uint4(0b0001),
    float4_e2m1fn(2):    uint4(0b0100),
    float4_e2m1fn(3):    uint4(0b0011),
    float4_e2m1fn(4):    uint4(0b0110),
    float4_e2m1fn(6):    uint4(0b0101),
    float4_e2m1fn(-0.0): uint4(0b1111),
    float4_e2m1fn(-0.5): uint4(0b1000),
    float4_e2m1fn(-1):   uint4(0b1010),
    float4_e2m1fn(-1.5): uint4(0b1001),
    float4_e2m1fn(-2):   uint4(0b1100),
    float4_e2m1fn(-3):   uint4(0b1011),
    float4_e2m1fn(-4):   uint4(0b1110),
    float4_e2m1fn(-6):   uint4(0b1101),
}

# You must use the same remapping scheme for both inputs (as using different
# remapping schemes for the two inputs does not shrink the circuit). You may NOT
# remap the output values (because this would make it take more microchip area
# to add the output values).

def write_your_multiplier_here(a0, a1, a2, a3, b0, b1, b2, b3):
    # 62 gates (33 AND, 18 XOR, 9 OR, 2 NOT). Bit roles: a0 = sign,
    # a1 = exponent high bit, a2 = exponent low bit, a3 = mantissa,
    # decoded under the custom INPUT_REMAP above.
    r1 = AND(a2, a1)
    r2 = AND(b2, b1)
    r3 = XOR(a2, b2)
    r4 = AND(a2, b2)
    r5 = XOR(a1, b1)
    r6 = XOR(r4, r5)
    r7 = AND(a1, b1)
    r8 = AND(r4, r5)
    r9 = XOR(a3, b3)
    r10 = AND(r3, r6)
    r11 = OR(r7, r8)
    r12 = NOT(r11)
    r13 = XOR(r10, r12)
    r14 = AND(r6, r13)
    r15 = AND(r3, r13)
    r16 = XOR(r14, r13)
    r17 = XOR(r15, r16)
    r18 = AND(a3, b3)
    r19 = AND(r17, r18)
    r20 = AND(r14, r18)
    r21 = AND(r3, r11)
    r22 = AND(r9, r21)
    r23 = XOR(a0, b0)
    r24 = AND(r17, r23)
    r25 = AND(a3, r1)
    r26 = AND(b3, r2)
    r27 = OR(r25, r26)
    r28 = NOT(r27)
    r29 = AND(r23, r28)
    r30 = AND(r18, r11)
    r31 = AND(r9, r15)
    r32 = AND(r10, r18)
    r33 = OR(r3, r9)
    r34 = AND(r6, r33)
    r35 = AND(r33, r11)
    r36 = AND(r16, r33)
    r37 = AND(r23, r13)
    r38 = OR(r14, r37)
    r39 = AND(r9, r10)
    r40 = AND(r15, r18)
    r41 = AND(r6, r11)
    r42 = OR(r23, r11)
    r43 = XOR(r41, r42)
    r44 = XOR(r21, r43)
    r45 = AND(r23, r44)
    r46 = XOR(r32, r23)
    r47 = OR(r19, r34)
    r48 = OR(r39, r40)
    r49 = OR(r20, r35)
    r50 = XOR(r22, r46)
    r51 = XOR(r37, r47)
    r52 = XOR(r44, r48)
    r53 = XOR(r45, r49)
    r54 = OR(r41, r50)
    r55 = XOR(r30, r23)
    r56 = XOR(r24, r36)
    r57 = AND(r28, r51)
    r58 = AND(r28, r52)
    r59 = AND(r28, r53)
    r60 = AND(r28, r54)
    r61 = AND(r28, r55)
    r62 = XOR(r31, r38)

    # res0 is most significant bit in two's complement. res8 is least significant
    # bit (with place value 1/4th)
    return r29, r61, r60, r59, r58, r57, r62, r56, r17

def format_fp4(fp4: float4_e2m1fn):
    return f"0b{int(fp4.view(uint4)):04b}"

def format_qi9(qi9: np.int16):
    upper_bits = qi9 & np.int16(-2**9)
    lower_bits = qi9 & np.int16(2**9 - 1)
    assert upper_bits == np.int16(-2**9) or upper_bits == np.int16(0)
    return f"0b{qi9 & lower_bits:09b}"

def fp4_to_list_of_bits(fp4: float4_e2m1fn):
    uint_value = int(fp4.view(uint4))
    return [(uint_value >> i) & 1 for i in reversed(range(4))]

# Examples
assert fp4_to_list_of_bits(float4_e2m1fn(0)) == [False, False, False, False]
assert fp4_to_list_of_bits(float4_e2m1fn(0.5)) == [False, False, False, True]
assert fp4_to_list_of_bits(float4_e2m1fn(-6)) == [True, True, True, True]


for a in range(0, 2**4):
    for b in range(0, 2**4):
        a_fp4: float4_e2m1fn = uint4(a).view(float4_e2m1fn)
        b_fp4: float4_e2m1fn = uint4(b).view(float4_e2m1fn)
        print(f"Multiplying {a_fp4} (FP4: {format_fp4(a_fp4)}) * {b_fp4} (FP4: {format_fp4(b_fp4)})")

        # Compute reference result
        expected_fp32 = a_fp4.astype(float32) * b_fp4.astype(float32)
        expected_qi9 = np.int16(np.round(expected_fp32 * 4))
        print(f"Expected result: {expected_fp32} (QI9: {format_qi9(expected_qi9)})")


        # Compute actual result, including using the remap
        a_bits = fp4_to_list_of_bits(INPUT_REMAP[a_fp4])
        b_bits = fp4_to_list_of_bits(INPUT_REMAP[b_fp4])
        actual_result_bits = write_your_multiplier_here(*a_bits, *b_bits)
        actual_result_qi9 = np.uint16(sum(bit << (8 - i) for i, bit in enumerate(actual_result_bits)))
        if actual_result_bits[0]: actual_result_qi9 += np.uint16(0b1111111000000000)
        actual_result_qi9 = actual_result_qi9.view(np.int16)

        actual_result_fp32 = float32(actual_result_qi9) * 0.25
        print(f"Actual result: {actual_result_fp32} (QI9: {format_qi9(actual_result_qi9)})")
        print()

        assert expected_qi9 == actual_result_qi9, "Actual result is not correct!"